# Generated by Django 3.2.5 on 2021-07-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
