# Generated by Django 3.2.5 on 2021-07-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsupdate',
            old_name='test',
            new_name='Creator',
        ),
    ]
