# Generated by Django 3.2.5 on 2021-07-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_test_newsupdate_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsupdate',
            old_name='Creator',
            new_name='newsCreator',
        ),
    ]
