# Generated by Django 3.2.5 on 2021-07-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='ss',
            field=models.FileField(blank=True, null=True, upload_to='feedback/'),
        ),
    ]
