# Generated by Django 3.2.5 on 2021-07-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeedback', '0003_auto_20210730_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.CharField(default='Test', max_length=130),
        ),
        migrations.AddField(
            model_name='thread',
            name='creator',
            field=models.CharField(default='test', max_length=130),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
