# Generated by Django 3.2.5 on 2021-07-30 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeedback', '0004_auto_20210730_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
