# Generated by Django 3.2.5 on 2021-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210709_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='modelDevUnit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
