# Generated by Django 3.2.5 on 2021-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_search_modeldevunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='modelText',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
