# Generated by Django 3.2.5 on 2021-07-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_search_modeltext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='search',
        ),
    ]
