# Generated by Django 3.2.5 on 2021-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_item_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='modelIntro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='modelStrength',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='modelUsage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='modelWeak',
            field=models.TextField(blank=True, null=True),
        ),
    ]
