# Generated by Django 3.2.5 on 2021-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210709_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='modelName',
            field=models.CharField(max_length=130),
        ),
    ]
