# Generated by Django 3.2.5 on 2021-07-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_search_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='modelName',
            field=models.CharField(max_length=130, verbose_name='Model Name'),
        ),
    ]
