# Generated by Django 3.2.5 on 2021-07-26 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_search_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='modelDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
