# Generated by Django 3.2.5 on 2021-07-26 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_alter_search_modeldate'),
    ]

    operations = [
        migrations.CreateModel(
            name='aiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Name of Model')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('wer', models.CharField(blank=True, max_length=130, null=True)),
                ('wordcount', models.IntegerField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
