# Generated by Django 3.2.5 on 2021-07-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='creator',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
