# Generated by Django 3.2.5 on 2021-07-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_aimodelgraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='wer',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='wordcount',
        ),
    ]
